source: source
destination: site
markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:title/
url: http://martin.elwin.com
multiviews: true
sass: false
haml: true
post_defaults:
  layout: blog_post
